#-------------------------------------------------------------------------------------------
# qemu
#-------------------------------------------------------------------------------------------
FROM debian:stretch-slim as qemu
RUN apt update && apt install -y qemu-user-static

#-------------------------------------------------------------------------------------------
# build stage
#-------------------------------------------------------------------------------------------
FROM arm32v7/python:3.7.11-slim-stretch as build
COPY --from=qemu /usr/bin/qemu-arm-static /usr/bin
COPY ./requirements.txt .

RUN apt-get update \
    && apt-get install -y build-essential libssl-dev libffi-dev cargo \
    && pip3 install --upgrade pip --no-cache-dir \
    && pip3 install -r requirements.txt --no-cache-dir

#-------------------------------------------------------------------------------------------
# target stage
#-------------------------------------------------------------------------------------------
FROM arm32v7/python:3.7.11-slim-stretch
COPY --from=build /usr/bin/qemu-arm-static /usr/bin
COPY --from=build /usr/local/lib/python3.7/site-packages /usr/local/lib/python3.7/site-packages
COPY ./*.py /app/

WORKDIR /app

CMD ["python", "-u", "/app/module.py"]
