#-------------------------------------------------------------------------------------------
# build stage
#-------------------------------------------------------------------------------------------
FROM debian:stretch-slim as qemu
RUN apt update && apt install -y qemu-user-static

#-------------------------------------------------------------------------------------------
# target stage
#-------------------------------------------------------------------------------------------
FROM arm32v7/python:3.7.11-slim-stretch
COPY --from=qemu /usr/bin/qemu-arm-static /usr/bin

COPY ./requirements.txt /app/
COPY ./*.json /app/
COPY ./*.py /app/

WORKDIR /app

RUN pip3 install -r requirements.txt

CMD ["python", "-u", "/app/module.py"]

